name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install NPM packages
        run: npm install -E

      - name: Build project
        run: npx vite build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./build
